apiVersion: v1
kind: Service
metadata:
  name: {{ include "upterm.fullname" . }}
  labels:
    {{- include "upterm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 22
      protocol: TCP
      targetPort: 22
      name: sshd
    {{- if .Values.websocket.enabled }}
    - port: 80
      protocol: TCP
      targetPort: 80
      name: ws
    {{- end }}
  selector:
    {{- include "upterm.selectorLabels" . | nindent 4 }}
